---
title: "Evaluating the other category"
author: "Sofía Meléndez Cartagena"
date: "3/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries
```{r}
library(tidyverse)
```

```{r}
library(PilasPack)
```

```{r}
library(lubridate)
```


## Data



```{r}
head(LabTags)
```

## Calculate Variables of interest

```{r}
All_test <- testApiToDates(DataFrame = Datos_all)

head(All_test)
```

```{r}
All_test <- testApiCalculateTurnaround(All_test)

head(All_test)
```

```{r}
All_test <- testApiMonthAsColumn(All_test)

head(All_test)
```


```{r}
All_test <- All_test %>%
  filter(createdAtDate > ymd("2020-03-9"))
```



```{r}
All_test <- All_test %>%
  filter(as.numeric(TatUploadSample) >= 0)
```



## Explore Col

```{r}
colnames(All_test)
```

## Isolate Numerical Variables

```{r}
TatsUpload <- All_test %>%
  select(processedByEntity.name,TatReportSample,TatUploadReport, TatUploadSample, createdAtDate) %>%
  mutate(CreatedYear = year(createdAtDate))%>%
  mutate(createdAtDate = month(createdAtDate, label = TRUE))%>%
  mutate(TatReportSample = as.numeric(TatReportSample)) %>%
  mutate(TatUploadReport = as.numeric(TatUploadReport)) %>%
  mutate(TatUploadSample = as.numeric(TatUploadSample)) %>%
  add_column(Tags = "NA")%>%
  mutate(Tags = as.character(Tags))

TatsUpload
```

## Count per Var



```{r}
 for(i in 1:length(LabTags$Nombre)){
     TatsUpload[TatsUpload$processedByEntity.name %in% LabTags[i,1],7] <- LabTags[i,3]
 }

TatsUpload[!(TatsUpload$processedByEntity.name %in% LabTags[,1]),7] <-"Other"

TatsUpload
```

## Isolate Other

```{r}
OtherTatUp <- TatsUpload %>%
  filter(Tags == "Other")

OtherTatUp
```

```{r}
PocosProb<-OtherTatUp %>%
  group_by(processedByEntity.name)%>%
  count()%>%
  filter(n <= 6)
```


```{r}
Analisis<-OtherTatUp %>%
  group_by(processedByEntity.name)%>%
  count()%>%
  filter(n > 6)
```

```{r}
MenosDe6Pruebas<-OtherTatUp[OtherTatUp$processedByEntity.name %in% PocosProb$processedByEntity.name,]

#write.csv(MenosDe6Pruebas, file = "../Menosde6Pruebas.csv")
```


```{r}
OtherTatUp <- OtherTatUp[OtherTatUp$processedByEntity.name %in% Analisis$processedByEntity.name,]

OtherTatUp
```

